POST http://streetcodernate.pythonanywhere.com/chat HTTP/1.1
content-type: application/json

{
    "query": { "event_details": "Landing web page for luxury space travel to Mars", "template_input_questions": ["About us","Our rockets","Earth to Mars in 2 days"]},
    "user_id": "bizlaunch",
    "premium": true
}


###

GET http://streetcodernate.pythonanywhere.com HTTP/1.1
content-type: application/json