POST http://127.0.0.1:5001/chat HTTP/1.1
content-type: application/json

{
    "query": "Yes. I have an AI Sales and Marketing agency that does research for companies and finds them high quality b2b leads. I live in ATL and want to connect to businesses around here.",
    "user_id": "bizlaunch",
    "premium": true
}


